name: Synchronize ASC API

on:
  workflow_dispatch:
  pull_request:
    branches: [ HEAD ]
  schedule:
    # run once per day
    - cron: '0 12 * * *'

jobs:
  diff_spec:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        echo "XXX"
