on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  schedule:
    # run once per day
    - cron: '0 12 * * *'

jobs:
  diff_spec:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
        # Grab the latest spec and perform some manual coersion to fix errors.
        # (see https://github.com/AvdLee/appstoreconnect-swift-sdk/pull/197)
        curl -fsSL -o - https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip
       
        # | bsdtar -xOf - | jq '.components.schemas.BundleIdPlatform.enum |= [ "IOS", "MAC_OS", "UNIVERSAL" ]' > Sources/OpenAPI/app_store_connect_api_2.0_openapi.json

        # If there are any differences, this workflow will fail
        # and send a notification. The api will then need to be
        # updated and tagged manually.
        git diff

